// Generated by https://quicktype.io

export interface MovieType {
  page:          number;
  results:       MovieResult[];
  total_pages:   number;
  total_results: number;
}

export interface MovieResult {
  adult:             boolean;
  backdrop_path:     string;
  genre_ids:         number[];
  id:                number;
  media_type:        MediaType;
  title?:            string;
  original_language: OriginalLanguage;
  original_title?:   string;
  overview:          string;
  popularity:        number;
  poster_path:       string;
  release_date?:     string;
  video?:            boolean;
  vote_average:      number;
  vote_count:        number;
  name?:             string;
  origin_country?:   string[];
  original_name?:    string;
  first_air_date?:   string;
}

export enum MediaType {
  Movie = "movie",
  Tv = "tv",
}

export enum OriginalLanguage {
  En = "en",
  Ko = "ko",
  Zh = "zh",
}
